name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  nestjs-test-build:
    runs-on: ubuntu-latest
    steps:
    - name: Source Code Checkout
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./build/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/nestjs-test:master
